services:
  ssemu:
    image: ssemu:latest
    hostname: server.ssemu
    container_name: server.ssemu
    volumes:
      - "../bin:/ssemu/bin"
    ports:
      - "0.0.0.0:28002:28002"
      - "0.0.0.0:28008:28008"
      - "0.0.0.0:28012:28012"
      - "0.0.0.0:28013:28013"
      - "8000:8000"
    depends_on:
      otel_collector:
        condition: service_started
    restart: unless-stopped
    networks:
      - ssemu

  otel_collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    hostname: otelcol.ssemu
    container_name: otelcol.ssemu
    volumes:
      - ../bin/otel/otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml
    command: --config /etc/otelcol/otel-collector-config.yml
    restart: unless-stopped
    depends_on:
      - jaeger
      - prometheus
    networks:
      - ssemu

  jaeger:
    image: jaegertracing/all-in-one:1.56
    hostname: jaeger.ssemu
    container_name: jaeger.ssemu
    ports:
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus.ssemu:9090
      - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=true
      - PROMETHEUS_QUERY_NORMALIZE_CALLS=true
      - PROMETHEUS_QUERY_NORMALIZE_DURATION=true
      - PROMETHEUS_QUERY_NAMESPACE=ssemu
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elastic.ssemu:9200
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: service_started
    networks:
      - ssemu

  prometheus:
    image: prom/prometheus:v2.49.1
    hostname: prometheus.ssemu
    container_name: prometheus.ssemu
    user: "1000:1000"
    ports:
      - "9090:9090"
    volumes:
      - "../bin/prometheus/config:/etc/prometheus"
      - "../bin/prometheus/data:/prometheus"
    command:
      - "--web.enable-remote-write-receiver"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"  
    restart: unless-stopped
    networks:
      - ssemu

  elasticsearch:
    image: elasticsearch:8.13.0
    hostname: elastic.ssemu
    container_name: elastic.ssemu
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    volumes:
      - ../bin/elastic:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - ssemu

networks:
  ssemu:
    driver: bridge
    name: network.ssemu
